# Generated by Django 2.1 on 2018-08-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierpatient',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
